Orillusion/orillusion

src/engine/gfx/graphics/webGpu/CanvasConfig.ts, src/engine/math/AnimationCurve.ts, src/engine/math/Bezier2D.ts, src/engine/math/Bezier3D.ts, src/engine/math/Color.ts, src/engine/math/Line.ts, src/engine/math/PolynomialCurve.ts, src/engine/math/Polynomials.ts
- add polynomials module
- add polynomialCurve module
- add line module
- add color module
- add Bezier3d module
- add Bezier2d module
- add animationCurve module
=> feat(math): add math lib

src/engine/core/pool/memory/MatrixDO.ts, src/engine/core/pool/memory/MemoryDO.ts, src/engine/core/pool/memory/MemoryInfo.ts
- add MemoryDO
- add MemoryInfo
=> feat(memory): add MemoryDO

src/engine/math/Rand.ts, src/engine/math/Random.ts, src/engine/math/Ray.ts, src/engine/math/Rect.ts, src/engine/math/TimeInterpolator.ts, src/engine/math/Triangle.ts, src/engine/math/UV.ts, src/engine/math/Vector2.ts, src/engine/math/Vector3.ts, src/engine/math/Vector4.ts
Add random numbers
Add ray detection
Add Triangle, Rect, UV,  TimeInterpolator
Add Vector2, Vector3, Vector4
=> feat(math): add math libs

src/engine/gfx/graphics/webGpu/core/buffer/ComputeGPUBuffer.ts, src/engine/gfx/graphics/webGpu/core/buffer/GPUBufferBase.ts, src/engine/gfx/graphics/webGpu/core/buffer/IndicesGPUBuffer.ts, src/engine/gfx/graphics/webGpu/core/buffer/VertexGPUBuffer.ts
add GPUBufferBase
add ComputeGPUBuffer
add IndicesGPUBuffer
add VertexGPUBuffer
=> feat(GPUBuffer): add GPUBuffer wrapper

src/engine/gfx/graphics/webGpu/core/uniforms/UniformNode.ts
=> feat(memory): add UniformNode

src/engine/gfx/generate/convert/BlurEffectCreator.ts, src/engine/gfx/generate/convert/ErpImage2CubeMap.ts, src/engine/gfx/generate/convert/TextureCubeStdCreator.ts, src/engine/gfx/generate/convert/TextureCubeUtils.ts
Added: BlurEffectCreator.ts
Added: ErpImage2CubeMap.ts
Added: TextureCubeStdCreator.ts
Added: TextureCubeUtils.ts
=> feat(webGPU): add create WebGPU texture cube code.

src/engine/assets/shader/glsl/Sky_glsl.ts, src/engine/assets/shader/materials/Lambert_shader.ts, src/engine/assets/shader/math/MathShader.ts, src/engine/assets/shader/post/Bloom_shader.ts, src/engine/assets/shader/post/GlobalFog_shader.ts, src/engine/assets/shader/quad/Quad_shader.ts, src/engine/assets/shader/sky/AtmosphericScatteringSky_shader.ts, src/engine/assets/shader/sky/CubeSky_Shader.ts
Add some materials classes, and post effect shaders.
Added: glsl/Sky_glsl.ts
Added: Lambert_shader.ts
Added: MathShader.ts
Added: Bloom_shader.ts
Added: GlobalFog_shader.ts
Added: Quad_shader.ts
Added: AtmosphericScatteringSky_shader.ts
Added: CubeSky_Shader.ts
=> feat(shader): Add shader module

src/engine/io/InputSystem.ts, src/engine/io/PickFire.ts, src/engine/io/PickResult.ts, src/engine/io/RayCastMeshDetail.ts, src/engine/io/TouchData.ts, src/engine/io/picker/PickCompute.ts
Add user input response script
Added: InputSystem.ts
Added: PickFire.ts
Added: PickResult.ts
Added: RayCastMeshDetail.ts
Added: TouchData.ts
Added: PickCompute.ts
=> feat(io): Add io files

src/engine/components/ColliderComponent.ts, src/engine/components/shape/BoxColliderShape.ts, src/engine/components/shape/CapsuleColliderShape.ts, src/engine/components/shape/ColliderShape.ts, src/engine/components/shape/MeshColliderShape.ts, src/engine/components/shape/SphereColliderShape.ts, src/engine/core/pool/ObjectPool.ts, src/engine/core/tree/kdTree/IKDTreeUserData.ts, src/engine/core/tree/kdTree/KDTreeEntity.ts, src/engine/core/tree/kdTree/KDTreeNode.ts, src/engine/core/tree/kdTree/KDTreeSpace.ts
Added: ColliderComponent.ts
Added: BoxColliderShape.ts
Added: CapsuleColliderShape.ts
Added: ColliderShape.ts
Added: MeshColliderShape.ts
Added: SphereColliderShape.ts
Added: ObjectPool.ts
Added: IKDTreeUserData.ts
Added: KDTreeEntity.ts
Added: KDTreeNode.ts
Added: KDTreeSpace.ts
=> feat(component): Add collider components and kdtree into engine.

src/engine/loader/FileLoader.ts, src/engine/loader/LoaderBase.ts, src/engine/loader/LoaderData.ts, src/engine/loader/LoaderFunctions.ts, src/engine/loader/LoaderManager.ts, src/engine/loader/parser/AtlasParser.ts, src/engine/loader/parser/B3DMParser.ts, src/engine/loader/parser/FntParser.ts, src/engine/loader/parser/I3DMParser.ts, src/engine/loader/parser/OBJParser.ts, src/engine/loader/parser/ParserBase.ts, src/engine/loader/parser/RGBEParser.ts, src/engine/loader/parser/b3dm/B3DMLoader.ts, src/engine/loader/parser/b3dm/B3DMLoaderBase.ts, src/engine/loader/parser/b3dm/FeatureTable.ts, src/engine/loader/parser/b3dm/arrayToString.ts, src/engine/loader/parser/b3dm/readMagicBytes.ts, src/engine/loader/parser/i3dm/I3DMLoader.ts, src/engine/loader/parser/i3dm/I3DMLoaderBase.ts, src/engine/loader/parser/tileRenderer/TileSet.ts, src/engine/loader/parser/tileRenderer/TilesRenderer.ts
Add loader and parser files
----
Added: FileLoader.ts
Added: LoaderBase.ts
Added: LoaderData.ts
Added: LoaderFunctions.ts
Added: LoaderManager.ts
Added: AtlasParser.ts
Added: B3DMParser.ts
Added: FntParser.ts
Added: I3DMParser.ts
Added: OBJParser.ts
Added: ParserBase.ts
Added: RGBEParser.ts
Added: B3DMLoader.ts
Added: B3DMLoaderBase.ts
Added: FeatureTable.ts
Added: arrayToString.ts
Added: readMagicBytes.ts
Added: I3DMLoader.ts
Added: I3DMLoaderBase.ts
Added: TileSet.ts
Added: TilesRenderer.ts
=> feat(loaderAndParser): Add loader and parser files

src/engine/util/AxisObject.ts, src/engine/util/BytesStream.ts, src/engine/util/CameraUtil.ts, src/engine/util/Convert.ts, src/engine/util/GeometryUtil.ts, src/engine/util/Global.ts, src/engine/util/KelvinUtil.ts, src/engine/util/Object3DUtil.ts, src/engine/util/ProfilerUtil.ts, src/engine/util/StringUtil.ts, src/engine/util/Time.ts, src/engine/util/Vector3Ex.ts, src/engine/util/ZSorterUtil.ts
- add AxisObject
- add BytesStream
- add CameraUtil
- add UUID
- add KelvinUtil
- add Object3DUtil
=> feat(util): add util files

src/engine/loader/parser/gltf/GLBParser.ts, src/engine/loader/parser/gltf/GLTFInfo.ts, src/engine/loader/parser/gltf/GLTFParser.ts, src/engine/loader/parser/gltf/GLTFSubParser.ts, src/engine/loader/parser/gltf/GLTFSubParserCamera.ts, src/engine/loader/parser/gltf/GLTFSubParserConverter.ts, src/engine/loader/parser/gltf/GLTFSubParserMaterial.ts, src/engine/loader/parser/gltf/GLTFSubParserMesh.ts, src/engine/loader/parser/gltf/GLTFSubParserSkeleton.ts, src/engine/loader/parser/gltf/GLTFSubParserSkin.ts, src/engine/loader/parser/gltf/TypeArray.ts, src/engine/loader/parser/gltf/extends/KHR_draco_mesh_compression.ts, src/engine/loader/parser/gltf/extends/KHR_lights_punctual.ts, src/engine/loader/parser/gltf/extends/KHR_materials_clearcoat.ts, src/engine/loader/parser/gltf/extends/KHR_materials_emissive_strength.ts, src/engine/loader/parser/gltf/extends/KHR_materials_ior.ts, src/engine/loader/parser/gltf/extends/KHR_materials_sheen.ts, src/engine/loader/parser/gltf/extends/KHR_materials_specular.ts, src/engine/loader/parser/gltf/extends/KHR_materials_transmission.ts, src/engine/loader/parser/gltf/extends/KHR_materials_unlit.ts, src/engine/loader/parser/gltf/extends/KHR_materials_variants.ts, src/engine/loader/parser/gltf/extends/KHR_materials_volume.ts, src/engine/loader/parser/gltf/extends/KHR_mesh_quantization.ts, src/engine/loader/parser/gltf/extends/KHR_texture_basisu.ts, src/engine/loader/parser/gltf/extends/KHR_texture_transform.ts
- add GLBParser
- add GLTFParser
=> feat(parser): add gltf parser

src/engine/gfx/renderJob/passRenderer/graphic/Graphic3DBatchRenderer.ts, src/engine/gfx/renderJob/passRenderer/graphic/Graphic3DFillRenderer.ts, src/engine/gfx/renderJob/passRenderer/graphic/Graphic3DFixedRenderPipeline.ts, src/engine/gfx/renderJob/passRenderer/graphic/Graphic3DLineBatchRenderer.ts, src/engine/gfx/renderJob/passRenderer/graphic/Graphic3DRender.ts, src/engine/gfx/renderJob/passRenderer/graphic/GraphicConfig.ts, src/engine/gfx/renderJob/passRenderer/graphic/Graphics3DShape.ts
- add Graphic3D
- add Graphics3DShape
- add Graphic3DBatchRenderer
- add Graphic3DFillRenderer
- add Graphic3DLineBatchRenderer
=> feat(Graphic3D): add wireframe graphics to draw

src/engine/components/audio/AudioListener.ts, src/engine/components/audio/PositionAudio.ts, src/engine/components/audio/StaticAudio.ts
StaticAudio
PositionAudio
AudioListener
=> feat(audio): add audio components

src/engine/components/SkeletonAnimationComponent.ts, src/engine/components/anim/skeletonAnim/Joint.ts, src/engine/components/anim/skeletonAnim/JointPose.ts, src/engine/components/anim/skeletonAnim/Skeleton.ts, src/engine/components/anim/skeletonAnim/SkeletonAnimationClip.ts, src/engine/components/anim/skeletonAnim/SkeletonAnimationClipState.ts, src/engine/components/anim/skeletonAnim/SkeletonAnimationCompute.ts, src/engine/components/anim/skeletonAnim/SkeletonPose.ts, src/engine/components/anim/skeletonAnim/buffer/SkeletonBlendComputeArgs.ts, src/engine/components/anim/skeletonAnim/buffer/SkeletonTransformComputeArgs.ts, src/engine/components/anim/skeletonAnim/shader/compute_skeleton_blend.ts, src/engine/components/anim/skeletonAnim/shader/compute_skeleton_transform.ts
add SkeletonAnimationComponent
add SkeletonAnimationClip
add SkeletonAnimationClipState
=> feat(SkeletonAnimation): add skeleton animation component

src/engine/components/controller/CameraControllerBase.ts, src/engine/components/controller/FirstPersonCameraController.ts, src/engine/components/controller/FlyCameraController.ts, src/engine/components/controller/HoverCameraController.ts, src/engine/components/controller/ThirdPersonCameraController.ts
add CameraControllerBase
add FirstPersonCameraController
add FlyCameraController
add HoverCameraController
add ThirdPersonCameraController
=> feat(Camera): add camera controller

src/engine/components/AtmosphericComponent.ts, src/engine/components/BillboardComponent.ts, src/engine/components/ComponentBase.ts, src/engine/components/Transform.ts, src/engine/components/post/PostProcessingComponent.ts, src/engine/components/renderer/GlobalIlluminationComponent.ts, src/engine/components/renderer/InstanceDrawComponent.ts, src/engine/components/renderer/MaterialComponent.ts, src/engine/components/renderer/MeshComponent.ts, src/engine/components/renderer/MeshRenderer.ts, src/engine/components/renderer/RenderNode.ts, src/engine/components/renderer/SkinnedMeshRenderer.ts, src/engine/components/renderer/SkyRenderer.ts
Add ECS files into engine.
----
Added: AtmosphericComponent.ts
Added: BillboardComponent.ts
Added: ComponentBase.ts
Added: Transform.ts
Added: PostProcessingComponent.ts
Added: GlobalIlluminationComponent.ts
Added: InstanceDrawComponent.ts
Added: MaterialComponent.ts
Added: MeshComponent.ts
Added: MeshRenderer.ts
Added: RenderNode.ts
Added: SkinnedMeshRenderer.ts
Added: SkyRenderer.ts
=> feat(ECS): Add ECS files

src/engine/materials/MaterialRegister.ts, src/engine/materials/PavementMaterial.ts, src/engine/materials/PhysicMaterial.ts, src/engine/materials/PointMaterial.ts, src/engine/materials/SkyMaterial.ts, src/engine/materials/UnLitMaterial.ts, src/engine/materials/effectPass/OutLinePass.ts
=> feat(materials): add materials

src/engine/shape/BoxGeometry.ts, src/engine/shape/CylinderGeometry.ts, src/engine/shape/PlaneGeometry.ts, src/engine/shape/SphereGeometry.ts, src/engine/shape/TorusGeometry.ts
=> feat(shape): add shape

vite.config.js
watch all `.ts` changes from /src
auto update exports in `index.ts`
=> feat: auto indexing exports from /src

src/math/Matrix4.ts
fix multiply function of matrix4
=> fix(matrix4): fix multiply function

samples/render/Sample_BlendMode.ts, samples/render/Sample_ChangeTexture.ts, samples/render/Sample_ShaderState.ts
=> feat(sample): Sample blend mode

samples/sky/Sample_AtmosphericSky.ts, samples/sky/Sample_BitmapCubeSky.ts, samples/sky/Sample_BitmapCubeStdSky.ts, samples/sky/Sample_HDRSky.ts, samples/sky/Sample_LDRSky.ts, samples/sky/Sample_SolidColorSky.ts
=> feat(sample): add sky texture samples

samples/index.ts, samples/lights/PointLightsScript.ts, samples/lights/Sample_DirectLight.ts, samples/lights/Sample_PointLight.ts, samples/lights/Sample_PointLightShadow.ts, samples/lights/Sample_SpotLight.ts, samples/lights/_PointLightsScript.ts, src/components/ComponentBase.ts, src/components/lights/LightBase.ts
Add sample of directLight and other lights.
=> feat(sample): add light sample

src/gfx/renderJob/post/OutlinePost.ts, src/io/OutlineManager.ts, src/io/OutlinePostData.ts
add outline manager to support control of outline effects
=> feat(outline): add outlineManager

CHANGELOG.md, README.md, package.json, src/gfx/graphics/webGpu/CanvasConfig.ts
=> bump v0.6.1

src/components/Transform.ts, src/components/lights/IESProfiles.ts, src/core/geometry/GeometryBase.ts, src/core/geometry/GeometryIndicesBuffer.ts, src/io/OutlinePostData.ts, src/math/AnimationCurve.ts, src/math/Bezier3D.ts, src/math/Color.ts, src/math/Matrix4.ts, test/math/Color.test.ts
=> refactor(form): refactor form to from

samples/loader/Sample_FlightHelmet.ts, samples/loader/Sample_LoadGLB.ts, samples/loader/Sample_LoadGLTF.ts, samples/loader/Sample_LoadJson.ts, samples/material/Sample_PBRMaterial.ts, samples/material/Sample_UVMove.ts, samples/render/Sample_BlendMode2.ts
Add samples of load glb/json file.
=> feat(sample): sample of loader

.github/CODE_OF_CONDUCT.md, .github/commit-convention.md, .github/contributing.md, README.md, vite.config.js
including 
- Code of Conduct
- Issue Reporting Guidelines
- Pull Request Guidelines
- Development Setup
- NPM Scripts
- Project Structure
=> docs: add contributing guide

samples/geometry/Sample_CustomGeometry.ts, samples/geometry/Sample_InternalGeometry.ts, samples/geometry/Sample_VertexAnimation.ts, src/core/geometry/GeometryBase.ts
=> feat(sample): sample of geometry

samples/animation/Sample_Skeleton.ts, samples/animation/Sample_Skeleton2.ts
prevent shadow flashing on animation samples
=> fix(sample): update shadowRameRate

samples/pick/MaterialStateComponent.ts, samples/pick/Sample_BoxColliderPick.ts, samples/pick/Sample_OutlineEffectPick.ts, samples/pick/Sample_PixelPick.ts, samples/utils/ExampleScene.ts
Add samples about pick.
And outlinePost used in sample.
=> feat(sample): Add sample about pick

samples/animation/Sample_PropertyAnimation.ts, src/components/anim/curveAnim/PropertyAnimClip.ts
=> feat(sample): add property animation sample

src/Engine3D.ts, src/components/Transform.ts, src/core/entities/Object3D.ts, src/gfx/renderJob/collect/ComponentCollect.ts, src/gfx/renderJob/collect/ShadowLightsCollect.ts
fix break component dependency for engine3D
=> fix(ComponentCollect): break component dependency for engine3D

samples/gui/Sample_UIVisible.ts, src/components/gui/GUIPick.ts, src/components/gui/core/GUIGeometry.ts, src/components/gui/core/GUIQuad.ts, src/components/gui/core/GUIShader.ts, src/components/gui/uiComponents/IUIInteractive.ts, src/components/gui/uiComponents/UIButton.ts, src/components/gui/uiComponents/UIComponentBase.ts, src/components/gui/uiComponents/UIImage.ts, src/components/gui/uiComponents/UIInteractive.ts, src/components/gui/uiComponents/UIPanel.ts, src/components/gui/uiComponents/UITextField.ts, src/components/gui/uiComponents/UITransform.ts, src/components/gui/uiComponents/ViewPanel.ts, src/components/gui/uiComponents/WorldPanel.ts
Add api to control visible of ui component
=> feat(gui): Add api to control visible of gui component

samples/gui/Sample_UIChangeParent.ts, src/components/ComponentBase.ts, src/components/IComponent.ts, src/components/Transform.ts, src/components/gui/core/GUIGeometryRebuild.ts, src/components/gui/uiComponents/UIButton.ts, src/components/gui/uiComponents/UIComponentBase.ts, src/components/gui/uiComponents/UIImage.ts, src/components/gui/uiComponents/UITextField.ts, src/components/gui/uiComponents/UITransform.ts
1, GUI component can update with changes in object3D hierarchy ;
2, Implement GUI component destruction logic .
=> feat(GUI): Improve GUI

src/gfx/graphics/webGpu/shader/RenderShader.ts, src/util/BoundUtil.ts
remove set render blend mode  when blendMode equal none
=> fix(blend): samples blended opt

samples/sky/Sample_AtmosphericSky.ts, src/assets/shader/sky/AtmosphericScatteringSky_shader.ts
=> fix(Sky): fix AtmosphericSky color

samples/post/Sample_Fog.ts, src/components/gui/core/GUIMesh.ts
add fog sample
fix guiMesh boundingbox
=> feat(fog): add fog sample

src/components/gui/uiComponents/UIImageGroup.ts, src/core/entities/Object3D.ts
fix error of function setImageType.
=> fix(GUI): fix setImageType of ImageGroup

samples/gui/Sample_UIButton.ts, samples/gui/panel/GUIPanelPOI.ts, src/components/gui/uiComponents/UIButton.ts, src/math/Color.ts
You can set the button transition mode to color mode.
=> feat(GUI): Add color transition mode to the UIButton

src/materials/LitMaterial.ts
Complete data for cloned shaders
=> fix(material): Complete data for cloned shaders

samples/lights/Sample_DirectLight.ts, samples/lights/Sample_DirectLightShadow.ts, samples/utils/ExampleScene.ts, samples/utils/GUIUtil.ts, src/components/AtmosphericComponent.ts, src/math/Matrix4.ts
Establish relative between Sky Box and other 3D object(For example sunlight) to ensure their data consistency.
=> feat(RelativeSky): Relative sky to sunlight

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/bug_report_zh.md
=> chore: update bug report template

src/Engine3D.ts, src/io/RayCastMeshDetail.ts, src/loader/parser/i3dm/I3DMLoader.ts, src/math/MathUtil.ts, src/math/Matrix4.ts, src/math/Ray.ts, src/math/Triangle.ts, src/math/Vector3.ts
BREAKING CHANGE: Replace cross with crossProduct method
=> chore(Vector3): remove cross method

src/assets/shader/compute/ErpImage2CubeMapCreateCube_cs.ts
Fix sky Rendering error in the MAC environment.
=> fix(AtmosphericScattering): Fix sky Rendering error in the MAC environment.

samples/base/Sample_BoundingBox.ts, src/components/ComponentBase.ts, src/components/Transform.ts, src/core/bound/Frustum.ts, src/core/entities/Entity.ts, src/core/entities/Object3D.ts
Add tags to entity to check for any changes in the bound, and optimize the repeated calculation of the bound
=> perf(BoundingBox): add isBoundChange tag to Entity

src/math/Matrix4.ts
Fix projection error in `ortho` & `orthoOffCenter` in #228
=> fix(matrix4): Fix ortho projection error

src/math/Matrix4.ts
Reverts Orillusion/orillusion#249
=> Revert "fix(matrix4): Fix ortho projection error"

samples/graphic/Sample_GraphicLine.ts, src/gfx/graphics/webGpu/core/uniforms/UniformNode.ts
=> feat: graphic

samples/benchmark/Sample_drawCall.ts, samples/lights/Sample_LightEnable.ts, src/assets/shader/lighting/LightingFunction_frag.ts, src/assets/shader/materials/program/ShadowMapping_frag.ts, src/components/Transform.ts, src/components/lights/LightBase.ts, src/gfx/renderJob/collect/ShadowLightsCollect.ts, src/gfx/renderJob/passRenderer/cluster/ClusterLightingRender.ts
fix light enable
fix light cast shadow
=> fix(light): fix light enable

samples/material/Sample_UVMove.ts, src/assets/shader/lighting/BxDF_frag.ts, src/gfx/graphics/webGpu/core/uniforms/UniformNode.ts, src/io/PickFire.ts
fix material uniformNode not update
opt pick collect
fix when no have light iblDiffuse is dark
=> fix: fix material uniformNode not update

samples/pick/Sample_OutlineEffectPick.ts, src/Engine3D.ts, src/assets/shader/compute/OutLineBlendColor_cs.ts, src/assets/shader/compute/OutlineCalcOutline_cs.ts, src/assets/shader/compute/Outline_cs.ts, src/gfx/renderJob/post/OutlinePost.ts, src/io/OutlinePostData.ts, src/setting/post/OutlineSetting.ts
Change the offline texture size of the outline to be modifiable through EngineSetting(textureScale).
=> improve(outline): improve outline effect

src/components/Transform.ts, src/core/entities/Entity.ts
=> fix: change number children

src/gfx/graphics/webGpu/Context3D.ts
=> fix(canvas): fix external canvas style

src/components/Transform.ts, src/components/gui/uiComponents/UITransform.ts, src/core/entities/Entity.ts
UITransform will be updated correctly
=> fix(GUI): UITransform will be updated correctly

src/components/gui/uiComponents/TextFieldLayout.ts
Character loss during text layout.
=> fix: Character loss during text layout.

packages/media-extention/ChromaKeyMaterial.ts, packages/media-extention/ImageMaterial.ts, packages/media-extention/VideoMaterial.ts, samples/graphic/Sample_GraphicMesh_Color.ts, samples/graphic/Sample_GraphicMesh_SpriteSheet.ts, samples/loader/Sample_LoadGLB.ts, samples/material/Sample_ClearCoat.ts, samples/utils/ExampleScene.ts, src/assets/shader/core/struct/VertexAttributeIndexShader.ts, src/assets/shader/lighting/BxDF_frag.ts, src/assets/shader/materials/UnLitTextureArray.ts, src/gfx/renderJob/passRenderer/graphic/new/Graphic3DMeshRenderer.ts, src/loader/parser/gltf/GLTFSubParserConverter.ts, src/materials/LitMaterial.ts, src/materials/SkyMaterial.ts, src/math/Color.ts, src/math/UV.ts, src/textures/BitmapTexture2DArray.ts
fix gltf sample
fix emissive color
=> fix: fix gltf sample

samples/physics/Sample_PhysicsCar.ts
=> feat(sample): update physics car sample

samples/gui/Sample_UIPerformance2.ts, src/Engine3D.ts, src/components/gui/GUIConfig.ts, src/components/gui/GUIPickHelper.ts, src/components/gui/core/GUIMaterial.ts, src/components/gui/core/GUIShader.ts, src/components/gui/uiComponents/UIInteractive.ts, src/components/gui/uiComponents/UIPanel.ts
=> perf: use pixelRatio from UIPanel.

src/materials/Material.ts
Shadow of double side materials.
=> fix: Shadow of double side materials.

samples/particle/Sample_CandleFlame.ts
- remove sample_candleflame maskMap
=> chore: remove sample_candleflame maskMap

src/components/gui/core/GUICanvas.ts
Solve the issues mentioned in #367.
=> chore: fix type #367

packages/graphic/compute/shape3d/Path2DShape3DCode_cs.ts, src/components/gui/uiComponents/UITransform.ts
Fix error when lineJoin is set to round.
=> fix: Error when lineJoin is set to round

package.json
=> build: add esbuild sourcemap option

samples/animation/Sample_CameraPathAnimation.ts
This PR adds a new sample, `Sample_CameraPathAnimation`, demonstrating editable camera path animations within the Orillusion engine. It features an interactive `AxisController` for real-time path point adjustments, alongside showcasing camera movements such as DualOrbit, FixedCamera, FixedTarget, and FreeCamera modes. This addition offers developers a practical tool for creating dynamic and customizable camera animations in their 3D projects.
=> feat(sample): add camera path animation sample

src/io/PickFire.ts
1. assign values with input event
2. simplify event.data with {worldPos, screenUv, meshID, worldNormal}
=> fix(pickfire): fix undefined values

src/assets/Res.ts, src/textures/BitmapTextureCube.ts
change to the right order: [+X, -X, +Y, -Y, +Z, -Z]
=> fix(doc): fix TextureCube order (#388)

src/components/controller/OrbitController.ts, src/io/InputSystem.ts
remove pointerleave pointerout
=> fix(inputsystem): capture pointer on pointerdown
