.github/workflows/ci.yml, package.json
Switch to Ubuntu runner, could use swiftshader (a CPU-based Vulkan API driver) as webgpu backend
Even though there are still some internal Vulkan errors, it could process WebGPU APIs for CI test.
Wait for Electron/Chromium further updates
=> fix(ci):  use swiftshader(cpu based vulkan driver) as webgpu adaptor

samples/base/Sample_Transform.ts, samples/index.ts, samples/loader/Sample_FlightHelmet.ts, samples/loader/Sample_LoadGLTF.ts, samples/material/Sample_CustomMaterial.ts, samples/material/Sample_PBR.ts, samples/material/Sample_PBRMaterial.ts, samples/material/Sample_RenderPassClean.ts, samples/material/Sample_ReplaceMaterial.ts, samples/material/Sample_UVMove.ts, samples/material/Sample_UnlitMaterial.ts, samples/material/script/UVMoveComponent.ts, samples/render/Sample_BlendMode2.ts, samples/render/Sample_CullMode.ts, samples/render/Sample_TextureSample.ts, samples/sky/Sample_AtmosphericSky.ts, samples/utils/GUIUtil.ts, test/components/test/TestComponents.ts
Examples of using various materials and modifying material properties.
Add GUIUtil file.
=> feat(sample): add samples about material

packages/media-extention/VideoTexture.ts, packages/media-extention/package.json, samples/material/Sample_VideoMaterial.ts
~~pause and play video before importExternalTexture~~
use native VideoFrame to force video decoding at rendering frameFate
=> fix(videoTexture): force video refresh at rendering frameRate

samples/animation/Sample_CurveAnimation.ts, samples/animation/Sample_MorphTarget.ts, samples/animation/Sample_Skeleton.ts, samples/animation/Sample_Skeleton2.ts, samples/animation/Sample_Skeleton3.ts, src/util/Object3DUtil.ts
Add samples to show how to use skeletal animation and property animation
=> feat(sample): samples of animation

samples/physics/Sample_Physics01.ts, samples/physics/Sample_PhysicsBox.ts
Example of using the Ammo physics engine
=> feat(sample): add sample about physics

src/gfx/graphics/webGpu/Context3D.ts
1. check external canvas initial size
2. remove unsued code
3. throw error if not support webgpu
=> fix(canvas): refine canvas init

samples/animation/Sample_PropertyAnimation.ts, src/components/anim/curveAnim/AnimationMonitor.ts, src/components/anim/curveAnim/PropertyHelp.ts
Fix parameters used for space conversion
=> fix(PropertyAnimation): space conversion

samples/animation/Sample_PropertyAnimation.ts
Replace the name of the default animation clip with the hard code parameter
=> fix(sample): fix propertyAnimation.

samples/loader/Sample_LoadGLB.ts, samples/loader/Sample_LoadGLTF2.ts, samples/loader/Sample_LoadJson.ts, src/components/controller/HoverCameraController.ts, src/core/bound/BoundingBox.ts, src/core/entities/Entity.ts, src/gfx/renderJob/passRenderer/graphic/Graphic3DRender.ts, src/math/Vector3.ts, src/textures/AtmosphericScatteringSky.ts, src/util/BoundUtil.ts, src/util/Object3DUtil.ts
Fix rendering objects being incorrectly culled by the camera
=> fix(culling): Camera frustum culling

src/core/bound/BoundingBox.ts, src/core/bound/BoundingSphere.ts, src/core/bound/IBound.ts, src/gfx/renderJob/passRenderer/graphic/Graphic3DRender.ts
The bounding of Object 3D has been corrected to world space
=> refactor(BoundingBox): delete worldMin and worldMax

src/loader/parser/b3dm/B3DMLoaderBase.ts, src/loader/parser/i3dm/I3DMLoaderBase.ts
fix unnecessary memory copy in ```B3DMLoaderBase``` and ```I3DMLoaderBase```
=> fix(loader): fix unnecessary memory copy

src/components/Transform.ts, src/math/Matrix4.ts, src/math/Quaternion.ts
Fix matrix calculation error when executing the lookAt function from a special angle(90/270).
=> fix(Matrix4): Fix matrix calculation error of lookAt

samples/material/Sample_PBRMaterial.ts, src/components/AtmosphericComponent.ts, src/components/Transform.ts, src/components/renderer/RenderNode.ts, src/core/entities/Entity.ts
fix transform localQuat
fix renderer enable
=> fix: fix renderer

samples/octree/Sample_OctTreeBox.ts, samples/octree/Sample_OctTreeFrustum.ts
=> fix(Octree): Improve Octree's sample

samples/lights/Sample_MovebleLight.ts
feat(sample): add moveble light sample
=> feat(sample): add moveble light sample

src/math/Matrix4.ts
The math library matrix4 has written e as an incorrect 3.
=> fix: math matrix4 type #387

src/components/controller/HoverCameraController.ts
1.fix(HoverCameraController):Using HoverCameraController together with UIButton may result in a conflict.
2.feat(HoverCameraController):Accessors and mutators have been added to the private property to allow for custom limitations on the pitch rotation angle.
3.fix(HoverCameraController):Fixed the bug occurred when in the top view.
=> fix(HoverCameraController):Using HoverCameraController together with UIButton may result in a conflict

samples/geometry/Sample_ReplaceGeometry.ts, src/components/renderer/MeshRenderer.ts, src/components/renderer/RenderNode.ts, src/loader/LoaderBase.ts
Fix: Fix the error of replacing the MeshRenderer's geometry.
=> fix(MeshRenderer): replace geometry error

CHANGELOG.md, README.md, package.json, samples/compute/Sample_Fluid.ts, samples/compute/Sample_FluidOptimize.ts, samples/compute/fluid/FluidRenderShader.ts, samples/compute/fluid/FluidRenderShaderOpt.ts, samples/geometry/Sample_ReplaceGeometry.ts, samples/lights/Sample_MovebleLight.ts, samples/pick/Sample_BoxColliderPick.ts, samples/pick/Sample_MeshColliderPick.ts, samples/pick/Sample_PixelPick.ts, src/assets/Res.ts, src/assets/shader/materials/program/ShadowMapping_frag.ts, src/components/gui/GUIPick.ts, src/components/gui/uiComponents/IUIInteractive.ts, src/components/gui/uiComponents/UIPanel.ts, src/components/renderer/MeshRenderer.ts, src/components/renderer/RenderNode.ts, src/event/eventConst/PointerEvent3D.ts, src/io/InputSystem.ts, src/io/PickFire.ts, src/loader/LoaderBase.ts, src/textures/BitmapTextureCube.ts
* **doc:** fix TextureCube order ([#388](https://github.com/Orillusion/orillusion/issues/388)) ([#421](https://github.com/Orillusion/orillusion/issues/421)) ([7e4e15d](https://github.com/Orillusion/orillusion/commit/7e4e15d1500d1e16e5a780123f78d602be9a9708))
* **MeshRenderer:** replace geometry error ([#415](https://github.com/Orillusion/orillusion/issues/415)) ([c79e287](https://github.com/Orillusion/orillusion/commit/c79e2878c61480583ea4a73188e0e81c395d0dcb))
* **PCF:** PCF shadow error ([#371](https://github.com/Orillusion/orillusion/issues/371)) ([c47257c](https://github.com/Orillusion/orillusion/commit/c47257c47d65c1e5c3ee4f0eae0b2bf42295561c))
* **pick:** fix undefined values ([#416](https://github.com/Orillusion/orillusion/issues/416)) …
=> release v0.8.2

packages/physics/Physics.ts, packages/physics/index.ts, packages/physics/package.json, packages/physics/rigidbody/Rigidbody.ts, packages/physics/softbody/ClothSoftbody.ts, packages/physics/softbody/RopeSoftbody.ts, packages/physics/softbody/SoftbodyBase.ts, packages/physics/utils/CollisionShapeUtil.ts, packages/physics/utils/PhysicsDragger.ts, samples/physics/Sample_Cloth.ts, samples/physics/Sample_Dominoes.ts, samples/physics/Sample_MultipleConstraints.ts, samples/physics/Sample_PhysicsBox.ts, samples/physics/Sample_Rope.ts, samples/physics/Sample_dofSpringConstraint.ts
本次提交引入了 `RopeSoftBody` 组件，增加了刚体拖拽功能，并增强了 `CollisionShapeUtil` 的功能，以扩展物理引擎的功能性和用户交互体验。
1. 新增 `RopeSoftBody` 组件：重构了软体模块，对布料组件进行了调整。同时基于此新增了绳索软体支持。
2. 实现物理对象拖拽器：允许用户通过鼠标与刚体进行交互。
3. 增强 `CollisionShapeUtil` ：添加了创建复杂碰撞形状的新API。
4. 示例：更新了部分物理方面的示例，并新增了两个示例用以演示新特性。
- 无明显性能影响，所有功能均已通过测试。
- 我对整个物理集成系统进行了详细的文档说明和相关示例，计划将其提交到 `orillusion-web` 仓库。
=> feat(physics): add RopeSoftBody, rigidbody dragger, and enhance collisionShapeUtil
